[mgr]
show_hidden = true

[plugin]
prepend_previewers = [
  # Archive previewer ouch
  { mime = "application/*zip", run = "ouch" },
  { mime = "application/x-tar", run = "ouch" },
  { mime = "application/x-bzip2", run = "ouch" },
  { mime = "application/x-7z-compressed", run = "ouch" },
  { mime = "application/x-rar", run = "ouch" },
  { mime = "application/x-xz", run = "ouch" },
  { mime = "application/xz", run = "ouch" },

  { mime = "text/markdown", run = "glow" },

  # Duckdb
  { mime = "text/csv", run = "duckdb" },
  { mime = "text/tab-separated-values", run = "duckdb" },
  { mime = "application/json", run = "duckdb" },
  { mime = "application/parquet", run = "duckdb" },
  { mime = "text/plain", run = "duckdb" },
  { mime = "application/vnd.ms-excel", run = "duckdb" },
  { mime = "application/x-sqlite3", run = "duckdb" },
  { mime = "application/duckdb", run = "duckdb" },
]
prepend_fetchers = [
  { url = "*", run = "git", group = "git" },
  { url = "*/", run = "git", group = "git" },
]
prepend_preloaders = [
  { url = "*.csv", run = "duckdb", multi = false },
  { url = "*.tsv", run = "duckdb", multi = false },
  { url = "*.json", run = "duckdb", multi = false },
  { url = "*.parquet", run = "duckdb", multi = false },
  { url = "*.txt", run = "duckdb", multi = false },
  { url = "*.xlsx", run = "duckdb", multi = false },
]

[opener]
extract = [
  { run = 'ouch d -y "%*"', desc = "Extract here with ouch", for = "windows" },
  { run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
]
