# use_nerdfont = true
[keybindings]
"Shift+f" = "focus search"
"Shift+l" = "focus library"
"Shift+q" = "focus queue"
"q" = "noop"
"p" = "playpause"
"y" = "share selected"
"Shift+y" = "share current"
"Shift-s" = "unsave"
"Ctrl+d" = "move down 10"
"Ctrl+u" = "move up 10"
"Esc" = "back"

[theme]
background = "#11111b"
primary = "#89b4fa"
secondary = "#94e2d5"
title = "#89b4fa"
playing = "#a6e3a1"
playing_bg = "#181825"
highlight = "#ee99a0"
highlight_bg = "#181825"
playing_selected = "#a6e3a1"
error = "#1e1e2e"
error_bg = "#f38ba8"
statusbar = "#89b4fa"
statusbar_bg = "#181825"
statusbar_progress = "#89b4fa"
cmdline = "#89b4fa"
cmdline_bg = "#181825"
