#!/usr/bin/env bash

command sesh connect "$(
  command sesh list --icons | fzf --tmux 80%,70% \
    --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '^A All | ^T Tmux | ^Z Zoxide | ^R Rename Sesh | ^X Kill Sesh | ^F Fd' \
    --bind 'ctrl-a:change-prompt(⚡ )+reload(command sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(  )+reload(command sesh list -t --icons)' \
    --bind 'ctrl-z:change-prompt(  )+reload(command sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-x:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(command sesh list --icons)' \
    --bind 'ctrl-r:execute(echo -n "New name: " > /dev/tty && read new_name < /dev/tty && tmux rename-session -t {2..} "$new_name" > /dev/tty 2>&1)+change-prompt(⚡  )+reload(command sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'command sesh preview {}'
)"
