return {
  {
    "mason-org/mason.nvim",
    event = "VeryLazy",
    cmd = { "Mason" },
    opts = {
      registries = {
        "lua:mason-registry.index",
        "github:mason-org/mason-registry",
      },
      ui = {
        border = "rounded",
        icons = {
          package_installed = "✓",
          package_pending = "➜",
          package_uninstalled = "✗",
        },
      },
    },
    keys = {
      { "<leader>ms", "<cmd>Mason<CR>", desc = "󰽤 Open Mason" },
    },
  },
  {
    "mason-org/mason-lspconfig.nvim",
    event = "VeryLazy",
    dependencies = {
      "mason-org/mason.nvim",
      "saghen/blink.cmp",
    },
    opts = {
      ensure_installed = {
        "basedpyright",
        "bashls",
        "biome",
        "clangd",
        "cmake",
        "cssls",
        "docker_language_server",
        "emmet_language_server",
        "gopls",
        "html",
        "jsonls",
        "lemminx",
        "lua_ls",
        "markdown_oxide",
        "marksman",
        "neocmake",
        "postgres_lsp",
        "ruff",
        "rumdl",
        "rust_analyzer",
        "tailwindcss",
        "taplo",
        "vtsls",
        "yamlls",
        "zls",
      },

      automatic_enable = {
        exclude = {
          "rumdl",
          "stylua",
        },
      },
    },
  },
  {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    dependencies = { "mason-org/mason.nvim" },
    event = "VeryLazy",
    opts = {
      ensure_installed = {
        "actionlint",
        "biome",
        "clang-format",
        "cmakelang",
        "cmakelint",
        "codelldb",
        "delve",
        "eslint_d",
        "go-debug-adapter",
        "gofumpt",
        "goimports",
        "golangci-lint",
        "golines",
        "gomodifytags",
        "google-java-format",
        "gotests",
        "impl",
        "hadolint",
        "js-debug-adapter",
        "json2go",
        "markdown-oxide",
        "marksman",
        "prettierd",
        "rumdl",
        "shellcheck",
        "shfmt",
        "sqruff",
        "stylua",
        "yamlfmt",
      },
    },
  },
}
